In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = sns.load_dataset('iris')

In [5]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [11]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [14]:
X = df.drop('species', axis=1)
y = df['species']

In [16]:
 X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.20, random_state=42)

In [17]:
from sklearn.neighbors import KNeighborsClassifier

In [19]:
knn = KNeighborsClassifier(n_neighbors=5)

In [20]:
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [21]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [22]:
knn.score(X_test, y_test)

1.0

In [23]:
from sklearn.svm import SVC

In [31]:
svm = SVC(C=30, kernel='linear', gamma='auto')

In [32]:
svm.fit(X_train, y_train)

SVC(C=30, gamma='auto', kernel='linear')

In [33]:
svm.score(X_test, y_test)

1.0

#**GRID SEARCH CV**

In [34]:
from sklearn.model_selection import GridSearchCV

In [35]:
gscv = GridSearchCV((svm), {
    'C': [1,10,20,30],
    'kernel': ['rbf','linear'],
    'gamma': ['auto', 'scale']
}, cv=5, return_train_score=False)

In [37]:
gscv.fit(X, y)

GridSearchCV(cv=5, estimator=SVC(C=30, gamma='auto', kernel='linear'),
             param_grid={'C': [1, 10, 20, 30], 'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'linear']})

In [38]:
results = pd.DataFrame(gscv.cv_results_)

In [39]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.008122,0.003031,0.005163,0.002306,1,auto,rbf,"{'C': 1, 'gamma': 'auto', 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.005024,0.001015,0.003736,0.000575,1,auto,linear,"{'C': 1, 'gamma': 'auto', 'kernel': 'linear'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.005458,0.000562,0.003739,0.000555,1,scale,rbf,"{'C': 1, 'gamma': 'scale', 'kernel': 'rbf'}",0.966667,0.966667,0.966667,0.933333,1.0,0.966667,0.021082,11
3,0.006189,0.002374,0.004302,0.001841,1,scale,linear,"{'C': 1, 'gamma': 'scale', 'kernel': 'linear'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
4,0.006839,0.002683,0.006140,0.002294,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
5,0.004632,0.000102,0.003472,0.000187,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.966667,1.0,0.973333,0.038873,7
6,0.004486,0.000084,0.003717,0.000878,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
7,0.005317,0.001725,0.003539,0.000532,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.966667,1.0,0.973333,0.038873,7
8,0.004159,0.000115,0.003272,0.000317,20,auto,rbf,"{'C': 20, 'gamma': 'auto', 'kernel': 'rbf'}",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,10
9,0.004658,0.001240,0.003138,0.000280,20,auto,linear,"{'C': 20, 'gamma': 'auto', 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,11
10,0.008562,0.002762,0.005893,0.002217,20,scale,rbf,"{'C': 20, 'gamma': 'scale', 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
11,0.004755,0.000803,0.003662,0.000626,20,scale,linear,"{'C': 20, 'gamma': 'scale', 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,11
12,0.004449,0.000068,0.003354,0.000095,30,auto,rbf,"{'C': 30, 'gamma': 'auto', 'kernel': 'rbf'}",0.966667,1.000000,0.900000,0.933333,1.0,0.960000,0.038873,14
13,0.004315,0.000118,0.003197,0.000146,30,auto,linear,"{'C': 30, 'gamma': 'auto', 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.900000,1.0,0.960000,0.048990,14
14,0.005673,0.001895,0.004205,0.001961,30,scale,rbf,"{'C': 30, 'gamma': 'scale', 'kernel': 'rbf'}",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,7
15,0.009959,0.001726,0.008086,0.003128,30,scale,linear,"{'C': 30, 'gamma': 'scale', 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.900000,1.0,0.960000,0.048990,14

In [40]:
results[['param_C','param_kernel', 'mean_test_score'] ]

    param_C param_kernel  mean_test_score
0         1          rbf         0.980000
1         1       linear         0.980000
2         1          rbf         0.966667
3         1       linear         0.980000
4        10          rbf         0.980000
5        10       linear         0.973333
6        10          rbf         0.980000
7        10       linear         0.973333
8        20          rbf         0.966667
9        20       linear         0.966667
10       20          rbf         0.980000
11       20       linear         0.966667
12       30          rbf         0.960000
13       30       linear         0.960000
14       30          rbf         0.973333
15       30       linear         0.960000

#**RANDOM SEARCH CV / RANDOMIZED SEARCH**

In [41]:
from sklearn.model_selection import RandomizedSearchCV

In [52]:
rscv = RandomizedSearchCV((svm), {
    'C': [1,10,20,30],
    'kernel': ['rbf','linear'],
    'gamma': ['auto', 'scale']
},n_iter = 4,cv=5, return_train_score=False)

In [53]:
rscv.fit(X, y)

RandomizedSearchCV(cv=5, estimator=SVC(C=30, gamma='auto', kernel='linear'),
                   n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'gamma': ['auto', 'scale'],
                                        'kernel': ['rbf', 'linear']})

In [54]:
results2 = pd.DataFrame(rscv.cv_results_)

In [55]:
results2[['param_C','param_kernel', 'mean_test_score'] ]

   param_C param_kernel  mean_test_score
0       20       linear         0.966667
1        1       linear         0.980000
2       20       linear         0.966667
3       10          rbf         0.980000