In [1]:
import numpy as np 
import pandas as pd

In [3]:
employees = pd.DataFrame({
    'employee_id': [1,2,3,4,5],
    'name': ['Sahil', 'Khushi', 'Sanchari', 'Nihal', 'Anik'],
    'department': ['Finance', 'HR', 'IT', 'DS', 'AIML'],
})

salaries = pd.DataFrame({
    'employee_id': [1,2,3,6,7],
    'salary':[60000,80000,65000,85000,75000],
    'bonus': [5000,6000,8000,10000,9000]
})

In [5]:
employees

   employee_id      name department
0            1     Sahil    Finance
1            2    Khushi         HR
2            3  Sanchari         IT
3            4     Nihal         DS
4            5      Anik       AIML

In [6]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000   6000
2            3   65000   8000
3            6   85000  10000
4            7   75000   9000

In [7]:
pd.merge(employees,salaries)

   employee_id      name department  salary  bonus
0            1     Sahil    Finance   60000   5000
1            2    Khushi         HR   80000   6000
2            3  Sanchari         IT   65000   8000

In [8]:
pd.merge(employees,salaries, on = 'employee_id', how = 'inner')

   employee_id      name department  salary  bonus
0            1     Sahil    Finance   60000   5000
1            2    Khushi         HR   80000   6000
2            3  Sanchari         IT   65000   8000

In [9]:
pd.merge(employees,salaries, on = 'employee_id', how = 'outer')

   employee_id      name department   salary    bonus
0            1     Sahil    Finance  60000.0   5000.0
1            2    Khushi         HR  80000.0   6000.0
2            3  Sanchari         IT  65000.0   8000.0
3            4     Nihal         DS      NaN      NaN
4            5      Anik       AIML      NaN      NaN
5            6       NaN        NaN  85000.0  10000.0
6            7       NaN        NaN  75000.0   9000.0

In [10]:
pd.merge(employees,salaries, on = 'employee_id', how = 'left')

   employee_id      name department   salary   bonus
0            1     Sahil    Finance  60000.0  5000.0
1            2    Khushi         HR  80000.0  6000.0
2            3  Sanchari         IT  65000.0  8000.0
3            4     Nihal         DS      NaN     NaN
4            5      Anik       AIML      NaN     NaN

In [11]:
pd.merge(employees,salaries, on = 'employee_id', how = 'right')

   employee_id      name department  salary  bonus
0            1     Sahil    Finance   60000   5000
1            2    Khushi         HR   80000   6000
2            3  Sanchari         IT   65000   8000
3            6       NaN        NaN   85000  10000
4            7       NaN        NaN   75000   9000

**CONCATINATION**

In [18]:

df1 = pd.DataFrame({
    'A': ['A0','A1','A2'],
    'B':['B0','B1','B2'],
    'C':['C0','C1','C2']
})

df2 = pd.DataFrame({
    'A': ['A3','A4','A5'],
    'B':['B3','B4','B5'],
    'C':['C3','C4','C5']
})

In [13]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [14]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [15]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

**JOINING 2 DATA FRAMES**

In [19]:
df1 = pd.DataFrame({
    'name':['Alice', 'Bob', 'Charlie']
}, index = [1,2,3])

df2 = pd.DataFrame({
    'score':[85,90,95]
}, index = [2,3,4])

In [20]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [21]:
df2

   score
2     85
3     90
4     95

In [22]:
df1.join(df2, how = 'outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   95.0

In [23]:
df2.join(df1, how = 'outer')

   score     name
1    NaN    Alice
2   85.0      Bob
3   90.0  Charlie
4   95.0      NaN