In [1]:
import numpy as np 
import pandas as pd

In [6]:
labels = ['a','b','c']
my_list =[10,20,30]
arr = np.array([10,20,30])
d = {1:10,2:20,3:30}

In [7]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [8]:
pd.Series(arr, index =labels)

a    10
b    20
c    30
dtype: int64

In [3]:
#DATA FRAME
data = {
    'Name' : ['John', 'Anna', 'Sahil', 'Khushi', 'Anik'],
    'Age': [15,25,24,19,18],
    'City':['New York', 'Paris', 'London', 'Spain', 'Germany'],
    'Salary':[65000,70000,56000,36000,48000]
}
df = pd.DataFrame(data)
df

     Name  Age      City  Salary
0    John   15  New York   65000
1    Anna   25     Paris   70000
2   Sahil   24    London   56000
3  Khushi   19     Spain   36000
4    Anik   18   Germany   48000

In [9]:
data_list = [
     ['John'	,15	,'New York',	65000],
    ['Anna' ,25,	'Paris',	70000],
    ['Sahil' ,24	,'London'	,56000],
    ['Khushi'	,19	,'Spain',	36000],
    ['Anik' ,18	,'Germany',	48000]
    ]
df2 = pd.DataFrame(data_list)
df2
columns = ["Name", "Age", "City", "Salary"]
df2 = pd.DataFrame(data_list, columns = columns)
df2

     Name  Age      City  Salary
0    John   15  New York   65000
1    Anna   25     Paris   70000
2   Sahil   24    London   56000
3  Khushi   19     Spain   36000
4    Anik   18   Germany   48000

In [10]:
df2['Name']

0      John
1      Anna
2     Sahil
3    Khushi
4      Anik
Name: Name, dtype: str

In [11]:
df2[['Name', 'Age']]

     Name  Age
0    John   15
1    Anna   25
2   Sahil   24
3  Khushi   19
4    Anik   18

In [18]:
df2['Designation'] = ['Doc', 'Engg.', 'Doc', 'Engg.', 'Doc']
df2

     Name  Age      City  Salary Designation
0    John   15  New York   65000         Doc
1    Anna   25     Paris   70000       Engg.
2   Sahil   24    London   56000         Doc
3  Khushi   19     Spain   36000       Engg.
4    Anik   18   Germany   48000         Doc

In [19]:
df2.drop('Designation', axis =1) #deletes desgnation temoporarily

     Name  Age      City  Salary
0    John   15  New York   65000
1    Anna   25     Paris   70000
2   Sahil   24    London   56000
3  Khushi   19     Spain   36000
4    Anik   18   Germany   48000

In [20]:
df2.drop('Designation', axis =1, inplace = True)
df2 #deleted permanently

     Name  Age      City  Salary
0    John   15  New York   65000
1    Anna   25     Paris   70000
2   Sahil   24    London   56000
3  Khushi   19     Spain   36000
4    Anik   18   Germany   48000

In [21]:
#SELECTING ROW
df2.loc[0]

Name          John
Age             15
City      New York
Salary       65000
Name: 0, dtype: object

In [22]:
df2.loc[[0,1]]

   Name  Age      City  Salary
0  John   15  New York   65000
1  Anna   25     Paris   70000

In [26]:
#SELECTING SUBSETS OF  ROW
df2.loc[[0,1]][['City','Salary']]

       City  Salary
0  New York   65000
1     Paris   70000

In [27]:
#CONDITION
df2[df2['Age'] >18]

     Name  Age    City  Salary
1    Anna   25   Paris   70000
2   Sahil   24  London   56000
3  Khushi   19   Spain   36000

In [31]:
df2[(df2['Age'] > 18) & (df2["City"] == 'Paris')]

   Name  Age   City  Salary
1  Anna   25  Paris   70000